services:
  - mongodb
jobs:
  include:
    - language: node_js
      node_js: 14
      script:
        - cd frontend
        - npm ci
        - ng test
    - dist: trusty
      language: java
      jdk: oraclejdk11
      before_install:
        - in credentials.tar.gz.enc -out credentials.tar.gz -d
        - tar -xzf credentials.tar.gz
      before_script:
        - mongo admin --eval 'db.createUser({user:"usuario",pwd:"secreto",roles:["readWrite"]});'
      script:
        - cd backend
        - mvn test
      deploy:
        provider: gae
        keyfile: client-secret.json
        project: gotacar

