services:
  - mongodb
before_script:
  - mongo gotacar --eval 'db.createUser({user:"usuario",pwd:"secreto",roles:["readWrite"]});'
jobs:
  include:
    - language: node_js
      node_js: 14
      script:
      - cd frontend
      - npm ci
      - ng test

    - dist: trusty
      language: java
      jdk: oraclejdk11
      script: 
        - cd backend 
        - mvn test
