services:
  - mongodb
jobs:
  include:
    - language: node_js
      node_js: 14
      script:
        - cd frontend
        - npm ci
        - ng test
      after_success:
        - ng build --prod
      deploy:
        skip_cleanup: true
        - provider: firebase
          token: $FB_DEPLOY
          on:
            branch: master
        - provider: firebase
          token: $FB_DEPLOY
          on:
            branch: develop
    - dist: trusty
      language: java
      jdk: oraclejdk11
      before_script:
        - mongo admin --eval 'db.createUser({user:"usuario",pwd:"secreto",roles:["readWrite"]});'
      script:
        - cd backend
        - mvn test
        - mv ../client-secret.json ./client-secret.json
      deploy:
        provider: gae
        keyfile: client-secret.json
        project: gotacar
        on:
          branch: master
before_install:
  - openssl aes-256-cbc -K $encrypted_2fd045226a67_key -iv $encrypted_2fd045226a67_iv
    -in client-secret.json.enc -out client-secret.json -d
